### ISSUE TITLE
Update to use node-rolling-spider 1.0 and Cylon.js 1.0

### ISSUE THREAD

**Issue by deadprogram** [ChrisTheBaron/cylon-rolling-spider#1]
It would be great to update this module to use the @voodootikigod 1.0 release of node-rolling-spider, as well as the Cylon.js 1.0 release.

**Comment by ChrisTheBaron** [comment]
Hey,

This has been done in the latest release.

Cheers, Chris

**Comment by deadprogram** [comment]
Thanks!
